### ISSUE TITLE
Library constants can't be set in XML

### ISSUE THREAD

**Issue by lenasrd** [pulseshift/ui5-lib-visualization#3]
Only the default value defined in ChartSeries.js (or ChartSeries-dbg.js) is noticed.

`<viz:ChartSeries type="ui5.viz.ChartSeriesType.Line">` won't have any effect, neither will
`<viz:ChartSeries type="line">`

**Comment by lenasrd** [comment]
The same applies for
`<viz:ChartSeries yAxis="ui5.viz.Axis.Y2">`

**Comment by fuchsvomwalde** [comment]
Hi, unfortunately this is a special behavior of UI5 and how it is handling data type constants in XML views.
Please use `<viz:ChartSeries type="Line">` (capital L, or the name of the final data type attribute) or in the second example you must use `<viz:ChartSeries yAxis="Y2">`.
