### ISSUE TITLE
x-Axis data obviously needs to be available by a certain point of time

### ISSUE THREAD

**Issue by lenasrd** [pulseshift/ui5-lib-visualization#32]
If the x axis data for the XML is delievered within a short delay (e.g. caused by a REST service call, or simply a timeout), in some cases this will cause errors.
Please notice this only relates to the x axis data. If the x axis data is defined within this unknown time span, the actual series data may be defined later but won't cause errors.

**Comment by fuchsvomwalde** [comment]
Should be fixed with 0.2.15, please retest.
